name: Build and Deploy Documentation

on:
  push:
    branches:
      - main  # or your default branch

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      # Step 1: Build Storybook first
      - name: Build Storybook
        run: npm run build-storybook
        
      # Step 2: Generate TypeDoc into a subdirectory of Storybook
      - name: Generate TypeDoc documentation
        run: npm run docs
        
      # Add debugging step to see what files were generated
      - name: Check TypeDoc output
        run: |
          echo "Files in API directory:"
          ls -la storybook-static/api/
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './storybook-static'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4